INSERT INTO TB_CONTA  (INSTITUICAO_FINANCEIRA, SALDO, TIPO_CONTA ) VALUES ('A', 300.00, 'CARTEIRA');
INSERT INTO TB_CONTA  (INSTITUICAO_FINANCEIRA, SALDO, TIPO_CONTA ) VALUES ('B', 150.00, 'CONTA_CORRENTE');
INSERT INTO TB_CONTA  (INSTITUICAO_FINANCEIRA, SALDO, TIPO_CONTA ) VALUES ('C', 0, 'CARTEIRA');
INSERT INTO TB_CONTA  (INSTITUICAO_FINANCEIRA, SALDO, TIPO_CONTA ) VALUES ('B', 50.00, 'POUPANCA');