# Inserir contas ao iniciar o projeto

INSERT INTO TB_CONTA  (INSTITUICAO_FINANCEIRA, SALDO, TIPO_CONTA ) VALUES ('instituição A', 300.00, 'CARTEIRA');
INSERT INTO TB_CONTA  (INSTITUICAO_FINANCEIRA, SALDO, TIPO_CONTA ) VALUES ('instituição B', 150.00, 'CONTA_CORRENTE');
INSERT INTO TB_CONTA  (INSTITUICAO_FINANCEIRA, SALDO, TIPO_CONTA ) VALUES ('instituição C', 0, 'CARTEIRA');
INSERT INTO TB_CONTA  (INSTITUICAO_FINANCEIRA, SALDO, TIPO_CONTA ) VALUES ('instituição B', 50.00, 'POUPANCA');